Repository buckaroo69/TQSPROJECT, pull requests merged in 2021-06, with the labels that each got.

#22 Feature:Prepared mainApp for iteration tests
  mainApp/src/main/java/logisticsmarshall/tqs/ua/controllers/LogisticsAPIController.java
  mainApp/src/main/java/logisticsmarshall/tqs/ua/controllers/LogisticsWebController.java
  mainApp/src/main/java/logisticsmarshall/tqs/ua/model/Company.java
  mainApp/src/main/java/logisticsmarshall/tqs/ua/model/Delivery.java
  mainApp/src/main/java/logisticsmarshall/tqs/ua/model/Driver.java
  mainApp/src/main/java/logisticsmarshall/tqs/ua/model/Payment.java
  mainApp/src/main/java/logisticsmarshall/tqs/ua/model/Reputation.java
  mainApp/src/main/java/logisticsmarshall/tqs/ua/model/User.java
  mainApp/src/main/java/logisticsmarshall/tqs/ua/services/DeliveryService.java
  mainApp/src/test/logisticsmarshall/tqs/ua/controllers/LogisticsAPIControllerTest.java
  mainApp/src/test/logisticsmarshall/tqs/ua/controllers/LogisticsWebControllerTest.java
Labels: tests

#32 Add menus
  clientApp/pom.xml
  clientApp/src/main/java/marchingfood/tqs/ua/config/ClientConfigs.java
  clientApp/src/main/java/marchingfood/tqs/ua/controller/AdminController.java
  clientApp/src/main/java/marchingfood/tqs/ua/exceptions/BadParameterException.java
  clientApp/src/main/java/marchingfood/tqs/ua/model/Client.java
  clientApp/src/main/java/marchingfood/tqs/ua/repository/ClientRepository.java
  clientApp/src/main/java/marchingfood/tqs/ua/repository/MenuRepository.java
  clientApp/src/main/java/marchingfood/tqs/ua/service/MenuService.java
  clientApp/src/main/resources/application.properties
  clientApp/src/main/resources/templates/cart.html
  clientApp/src/main/resources/templates/index.html
  clientApp/src/main/resources/templates/login.html
  clientApp/src/main/resources/templates/menu.html
  clientApp/src/main/resources/templates/profile.html
  clientApp/src/main/resources/templates/restaurant.html
  clientApp/src/main/resources/templates/restaurantDash.html
  clientApp/src/main/resources/templates/signup.html
  clientApp/src/test/java/marchingfood/tqs/ua/controller/MenuCRUDTest.java
  mainApp/src/test/java/logisticsmarshall/tqs/ua/controllers/LogisticsAPIControllerTest.java
  mainApp/src/test/java/logisticsmarshall/tqs/ua/controllers/LogisticsWebControllerTest.java
Labels: enhancement, frontend, marshingFood, tests

#36 178256550 178256970 Feature:Delivery posting+getting+test refactor
  mainApp/src/main/java/logisticsmarshall/tqs/ua/configs/WebSecurityConfig.java
  mainApp/src/main/java/logisticsmarshall/tqs/ua/controllers/LogisticsAPIController.java
  mainApp/src/main/java/logisticsmarshall/tqs/ua/repository/DeliveryRepository.java
  mainApp/src/main/java/logisticsmarshall/tqs/ua/services/DeliveryService.java
  mainApp/src/test/java/logisticsmarshall/tqs/ua/controllers/LogisticsAPIControllerTest.java
Labels: backend, enhancement, logisticsMarshall, tests

#37 178257161 edit menus
  clientApp/src/main/java/marchingfood/tqs/ua/controller/AdminController.java
  clientApp/src/main/java/marchingfood/tqs/ua/model/Menu.java
  clientApp/src/main/java/marchingfood/tqs/ua/service/MenuService.java
  clientApp/src/main/resources/static/css/bootstrap.min.css
  clientApp/src/main/resources/templates/restaurantDash.html
  clientApp/src/test/java/marchingfood/tqs/ua/controller/MenuCRUDTest.java
  clientApp/src/test/java/marchingfood/tqs/ua/service/MenuServiceTest.java
Labels: backend, enhancement, frontend, marshingFood, tests

#38 178450737 preload menus
  clientApp/src/main/java/marchingfood/tqs/ua/config/DataSetup.java
  clientApp/src/main/java/marchingfood/tqs/ua/model/Menu.java
  clientApp/src/main/java/marchingfood/tqs/ua/service/MenuService.java
  clientApp/src/main/resources/templates/restaurantDash.html
  clientApp/src/test/java/marchingfood/tqs/ua/controller/MenuCRUDTest.java
Labels: backend, enhancement, frontend, marshingFood, tests

#43 178256970 - Client delivery post
  clientApp/pom.xml
  clientApp/src/main/java/marchingfood/tqs/ua/config/DataSetup.java
  clientApp/src/main/java/marchingfood/tqs/ua/config/DeliveryConfigs.java
  clientApp/src/main/java/marchingfood/tqs/ua/controller/DeliveryController.java
  clientApp/src/main/java/marchingfood/tqs/ua/repository/DeliveryRepository.java
  clientApp/src/main/java/marchingfood/tqs/ua/service/CartService.java
  clientApp/src/main/java/marchingfood/tqs/ua/service/DeliveryService.java
  clientApp/src/main/java/marchingfood/tqs/ua/service/MenuService.java
  clientApp/src/main/java/marchingfood/tqs/ua/service/UserService.java
  clientApp/src/main/resources/static/css/bootstrap.min.css
  clientApp/src/main/resources/static/css/cart.css
  clientApp/src/main/resources/static/css/custom.css
  clientApp/src/main/resources/templates/cart.html
  clientApp/src/main/resources/templates/deliveryDash.html
  clientApp/src/main/resources/templates/deliveryStatus.html
  clientApp/src/main/resources/templates/index.html
  clientApp/src/main/resources/templates/login.html
  clientApp/src/main/resources/templates/menu.html
  clientApp/src/main/resources/templates/profile.html
  clientApp/src/main/resources/templates/restaurant.html
  clientApp/src/main/resources/templates/restaurantDash.html
  clientApp/src/main/resources/templates/signup.html
  clientApp/src/test/java/marchingfood/tqs/ua/controller/DeliveryCRUDTest.java
  clientApp/src/test/java/marchingfood/tqs/ua/service/DeliveryServiceTest.java
Labels: bug, enhancement, marshingFood, tests

#52 Refactor: Marching foods delivery + cart
  clientApp/src/main/java/marchingfood/tqs/ua/controller/DeliveryController.java
  clientApp/src/main/java/marchingfood/tqs/ua/repository/DeliveryRepository.java
  clientApp/src/main/java/marchingfood/tqs/ua/service/CartService.java
  clientApp/src/main/resources/static/css/index.css
  clientApp/src/main/resources/static/css/style.css
  clientApp/src/main/resources/templates/cart.html
  clientApp/src/main/resources/templates/index.html
  clientApp/src/main/resources/templates/restaurant.html
Labels: backend, frontend, marshingFood

#60 Logistics marshall delivery state
  mainApp/src/main/java/logisticsmarshall/tqs/ua/configs/UtilConfigs.java
  mainApp/src/main/java/logisticsmarshall/tqs/ua/controllers/LogisticsAPIController.java
  mainApp/src/main/java/logisticsmarshall/tqs/ua/utils/Utils.java
  mainApp/src/test/java/logisticsmarshall/tqs/ua/controllers/LogisticsAPIControllerTest.java
  mainApp/src/test/java/logisticsmarshall/tqs/ua/services/DeliveryServiceTest.java
Labels: logisticsMarshall, tests

#62 Logistics marshall delivery state
  mainApp/src/main/java/logisticsmarshall/tqs/ua/configs/DataSetup.java
  mainApp/src/main/java/logisticsmarshall/tqs/ua/controllers/LogisticsWebController.java
  mainApp/src/main/java/logisticsmarshall/tqs/ua/model/Delivery.java
  mainApp/src/main/java/logisticsmarshall/tqs/ua/model/Driver.java
  mainApp/src/main/java/logisticsmarshall/tqs/ua/model/Reputation.java
  mainApp/src/main/java/logisticsmarshall/tqs/ua/model/User.java
  mainApp/src/main/java/logisticsmarshall/tqs/ua/repository/DeliveryRepository.java
  mainApp/src/main/java/logisticsmarshall/tqs/ua/repository/ReputationRepository.java
  mainApp/src/main/java/logisticsmarshall/tqs/ua/services/DeliveryService.java
  mainApp/src/main/java/logisticsmarshall/tqs/ua/services/ReputationService.java
  mainApp/src/main/resources/templates/businessOwnerProfile.html
  mainApp/src/main/resources/templates/mainDash.html
  mainApp/src/main/resources/templates/workerProfile.html
Labels: backend, enhancement, frontend, logisticsMarshall

#73 Logistics marshall api delivery - Ratings
  mainApp/src/main/java/logisticsmarshall/tqs/ua/controllers/LogisticsAPIController.java
  mainApp/src/main/java/logisticsmarshall/tqs/ua/repository/DriverRepository.java
  mainApp/src/main/java/logisticsmarshall/tqs/ua/repository/ReputationRepository.java
  mainApp/src/main/java/logisticsmarshall/tqs/ua/services/CompanyService.java
  mainApp/src/main/java/logisticsmarshall/tqs/ua/services/DriverService.java
  mainApp/src/main/java/logisticsmarshall/tqs/ua/services/ReputationService.java
  mainApp/src/test/java/logisticsmarshall/tqs/ua/controllers/LogisticsAPIControllerTest.java
Labels: backend, logisticsMarshall, tests

#75 Post Ratings + tests + view ratings
  mainApp/src/main/java/logisticsmarshall/tqs/ua/controllers/LogisticsAPIController.java
  mainApp/src/main/resources/templates/mainDash.html
  mainApp/src/test/java/logisticsmarshall/tqs/ua/controllers/LogisticsAPIControllerTest.java
Labels: logisticsMarshall, tests

#79 Small changes to frontend + an error solved
  mainApp/src/main/java/logisticsmarshall/tqs/ua/controllers/LogisticsWebController.java
  mainApp/src/main/resources/static/images/company.jpg
  mainApp/src/main/resources/static/images/driver.jpg
  mainApp/src/main/resources/templates/info.html
Labels: enhancement, frontend

#97 Integration tests main
  .github/workflows/build.yml
  mainApp/pom.xml
  mainApp/src/test/java/logisticsmarshall/tqs/ua/controllers/MainCompanyIT.java
  mainApp/src/test/java/logisticsmarshall/tqs/ua/controllers/MainDriverIT.java
  mainApp/src/test/java/logisticsmarshall/tqs/ua/controllers/MainRegisterCompanyIT.java
  mainApp/src/test/java/logisticsmarshall/tqs/ua/controllers/MainRegisterDriverIT.java
Labels: tests
